name: Build macOS Application

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build application
      run: |
        pyinstaller --windowed --name MagnetLinkExtractor1 magnet_extractor.py
        cp -r dist/MagnetLinkExtractor1.app MagnetLinkExtractor1.app
        
    - name: Create DMG installer
      run: |
        brew install create-dmg
        create-dmg \
          --volname "MagnetLinkExtractor1 Installer" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "MagnetLinkExtractor1.app" 200 190 \
          --hide-extension "MagnetLinkExtractor1.app" \
          --app-drop-link 600 190 \
          "MagnetLinkExtractor1.dmg" \
          "MagnetLinkExtractor1.app/"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MagnetLinkExtractor1-macOS
        path: MagnetLinkExtractor1.dmg
